name:                mono-pair
version:             0.0.0.1
github:              "larthia/mono-pair"
license:             BSD3
author:              "Nicola Bonelli"
maintainer:          "nicola@larthia.com"
copyright:           "2021 Nicola Bonelli"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/maybe#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - text
    - vector
    - serialise
    - cborg
    - binary

tests:
  mono-pair-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mono-pair
    - aeson
    - bytestring
    - serialise
